app/accounts/urls.py
from django.urls import path
from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('activate/<uuid:username>/', views.UserActivateView.as_view(), name='user_activate'),
    path('my_profile/', views.UserProfileView.as_view(), name='my_profile'),
]

app/settings/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('timeboard/', include('timeboard.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/timeboard/urls.py
from django.urls import path
from timeboard import views


app_name = 'timeboard'
urlpatterns = [
    path('hello_world/', views.hello_world, name='hello_world'),
    path('', views.IndexView.as_view(), name='index'),
]

app/accounts/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models


def user_avatar(instance, filename):
    return 'avatar/{0}/{1}'.format(instance.id, filename)


class User(AbstractUser):
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    email = models.EmailField('email address', unique=True)
    avatar = models.FileField(upload_to=user_avatar)

app/timeboard/models.py
from django.db import models

# Create your models here.

app/accounts/forms.py
import uuid

from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.forms import ValidationError

from django.urls import reverse
from django.core.mail import send_mail
from django.conf import settings


class SignUpForm(forms.ModelForm):
    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label="Password confirmation",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text="Enter the same password as before, for verification.",
    )

    class Meta:
        model = get_user_model()
        fields = (
            'email',
            # 'password',
        )

    def clean_email(self):
        """
        :return: email in low register
        """
        email = self.cleaned_data.get("email")
        return email.lower()

    def clean(self):
        """
        check password1 = password2
        :return: ValidationError
        """
        cleaned_data = super().clean()
        if not self.errors:
            if cleaned_data['password1'] != cleaned_data['password2']:
                raise forms.ValidationError('Passwords missmatch!')

        return cleaned_data

    def _post_clean(self):
        """
        validation password
        :return: ValidationError
        """
        super()._post_clean()
        password = self.cleaned_data.get("password2")
        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except ValidationError as error:
                self.add_error("password2", error)

    def save(self, commit=True):
        """
        save User object and send email
        """
        instance = super().save(commit=False)
        instance.username = str(uuid.uuid4())
        instance.set_password(self.cleaned_data['password1'])
        instance.is_active = False

        if commit:
            instance.save()

        self._send_activation_email()

        return instance

    def _send_activation_email(self):
        """
        generate activation link send email
        """

        subject = 'Activate Your Account'
        body = f'''
            Activation link: {settings.HTTP_SCHEMA}://{settings.DOMAIN}{reverse('accounts:user_activate',
                                                                                args=(self.instance.username, ))}
        '''
        send_mail(
            subject,
            body,
            settings.EMAIL_HOST_USER,
            [self.instance.email],
            fail_silently=False,
        )

app/accounts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views import generic
from django.urls import reverse_lazy
from accounts.forms import SignUpForm


class SignUpView(generic.CreateView):
    queryset = get_user_model().objects.all()
    template_name = 'accounts/signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('timeboard:index')


class UserActivateView(generic.RedirectView):
    pattern_name = 'timeboard:index'

    def get(self, request, *args, **kwargs):
        username = kwargs.pop('username')
        user = get_object_or_404(get_user_model(), username=username)

        if user.is_active:
            pass
        else:
            user.is_active = True
            user.save()

        response = super().get(request, *args, **kwargs)
        return response


class UserProfileView(LoginRequiredMixin, generic.UpdateView):
    queryset = get_user_model().objects.all()
    template_name = 'accounts/my_profile.html'
    success_url = reverse_lazy('timeboard:index')
    fields = (
        'first_name',
        'last_name',
        'avatar',
    )

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     queryset = queryset.filter(id=self.queryset.user.id)
    #     return queryset

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'User Profile'
        return context

app/timeboard/views.py
# from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic


# Create your views here.
def hello_world(request):
	name = request.GET.get('name')
	result = ''
	if not request.GET.get('name'):
		result = 'Hello, World!'
	else:
		result = 'Hello, ' + name + '!'
	return HttpResponse(result)


class IndexView(generic.TemplateView):
	template_name = 'timeboard/index.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = 'Tasks'
		return context

app/accounts/templates/accounts/my_profile.html
{% extends 'timeboard/base.html' %}
{% load crispy_forms_filters %}

{% block main_content %}
    {% if request.user.avatar %}
        <img src="{{ request.user.avatar.url }}" width="100" height="100">
    {% endif %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <div>
            <a href="{% url 'password_change' %}">Change password?</a>
        </div>
        <br>
        <button type=submit class="btn btn-success">Update</button>
    </form>
{% endblock main_content %}

app/accounts/templates/accounts/signup.html
{% extends 'timeboard/base.html' %}
{% load crispy_forms_filters %}

{% block main_content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h4 class="display-5">Sign Up</h4>
    </div>
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <form method="post" class="needs-validation" novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                <a href="{% url 'password_reset' %}">Forgot password?</a>
                <br><br>
                <button type=submit class="btn btn-success btn-block">Send</button>
            </form>
        </div>
        <div class="col-sm-4"></div>
    </div>
{% endblock main_content %}

app/timeboard/templates/timeboard/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{{ title }}</title>

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
              crossorigin="anonymous">
    </head>

    <body>
        {% load static %}
        {# NAVBAR #}
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3
                    fixed-top bg-white border-bottom shadow-sm">
            <a href="{% url 'timeboard:index' %}">
                <img src="{% static "img/currency_exchange.jpg" %}"
                     alt=""
                     style="margin-left: 20px; margin-right: 3px;"
                     height="44">
            </a>
            <h4 class="my-0 mr-md-auto font-weight-normal" style="padding-left: 10px;">
                Timeboard Project
            </h4>

            <nav class="my-2 my-md-0 mr-md-3">
                <a class="p-2 text-dark" href="{% url 'timeboard:index' %}">Active tasks</a>
            </nav>
            {% if request.user.is_authenticated %}
                {% if request.user.avatar %}
                    <img src="{{ request.user.avatar.url }}"
                         alt=""
                         style="margin-left: 20px; margin-right: 3px;"
                         width="44"
                         height="44">
                {% endif %}
                <a class="btn btn-outline-info"
                   style="margin-right: 3px;"
                   href="{% url 'accounts:my_profile' %}">{{ request.user.email }}</a>
                <a class="btn btn-outline-warning"
                   style="margin-right: 30px;"
                   href="{% url 'logout' %}">LogOut</a>
            {% else %}
                <a class="btn btn-outline-success"
                   style="margin-right: 3px;"
                   href="{% url 'login' %}">LogIn</a>
                <a class="btn btn-outline-warning"
                   style="margin-right: 30px;"
                   href="{% url 'accounts:signup' %}">SignUp</a>
            {% endif %}
        </div>

        {# MAIN #}
        <main role="main" class="container" style="padding-top: 40px;">
            {# HEADER #}
            <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                <h4 class="display-5">{{ title }}</h4>
            </div>
            {# CONTENT #}
            <div class="container mx-auto">
            {% block main_content %}
            {% endblock main_content %}
            </div>
            {# FOOTER #}
            <footer class="pt-4 my-md-5 pt-md-5 border-top">
                <div class="row">
                    <div class="col-6 col-md">
                        <h5>Features</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="#">Cool stuff</a></li>
                            <li><a class="text-muted" href="#">Random feature</a></li>
                            <li><a class="text-muted" href="#">Team feature</a></li>
                            <li><a class="text-muted" href="#">Stuff for developers</a></li>
                            <li><a class="text-muted" href="#">Another one</a></li>
                            <li><a class="text-muted" href="#">Last time</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Resources</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="#">Resource</a></li>
                            <li><a class="text-muted" href="#">Resource name</a></li>
                            <li><a class="text-muted" href="#">Another resource</a></li>
                            <li><a class="text-muted" href="#">Final resource</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>About</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="#">Team</a></li>
                            <li><a class="text-muted" href="#">Locations</a></li>
                            <li><a class="text-muted" href="#">Privacy</a></li>
                            <li><a class="text-muted" href="#">Terms</a></li>
                        </ul>
                    </div>
                </div>
            </footer>
        </main>

        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
                integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
                crossorigin="anonymous">
        </script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
                crossorigin="anonymous">
        </script>
    </body>
</html>

app/timeboard/templates/timeboard/index.html
{% extends 'timeboard/base.html' %}

{% block main_content %}
    <div class="container-fluid mb-3 text-center">
        <p>Список моих задач</p>
    </div>
 {% endblock main_content %}